name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Test-Files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: before_script
        run: |         
          date
          uname -a
          pip install --upgrade pip
          printenv | sort

      - name: testScripts
        run: |
          ls -al
          cd src
          make test

  Build:
    needs: Test-Files
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - name: build
        run: |
          pip install pyinstaller
          cd 
          pyinstaller --onefile main.py
      
      - name: GIT Commit
        if: github.event_name == 'push'
        run: |
          git checkout "build"
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add dist build
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push


            
