name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Test-Files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: before_script
        run: |         
          date
          uname -a
          pip install --upgrade pip
          printenv | sort

      - name: testScripts
        run: |
          ls -al
          cd src
          make test
      
      - name: createEXE
        run: |
          ls -al
          cd src
          pip install pyinstaller
          pyinstaller main.py

      - name: Deploy
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: master
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
