name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Test-Files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: before_script
        run: |         
          date
          uname -a
          pip install --upgrade pip
          printenv | sort

      - name: testScripts
        run: |
          ls -al
          cd src
          make test
      
      - name: createEXE
        run: |
          ls -al
          cd src
          pyinstaller main.py

      - uses: actions/upload-artifact@v2
        with:
          name: my-exe
          path: src/dist/windows
