name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Test-Files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: before_script
        run: |         
          date
          uname -a
          pip install --upgrade pip
          printenv | sort

      - name: testScripts
        run: |
          ls -al
          cd src
          make test

  Build:
    needs: Test-Files
    runs-on: ubuntu-latest
    steps:
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      run: ls
      with:
        path: src

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: build


            
