name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Test-Files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: before_script
        run: |         
          date
          uname -a
          pip install --upgrade pip
          printenv | sort

      - name: testScripts
        run: |
          ls -al
          cd src
          make test

  Build:
    needs: Test-Files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Create local changes
      run: |
        cd src
        pip install pyinstaller
        pyinstaller --onefile main.py
        cd ..

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}


            
